// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmonpfpewxuyshmipzhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtb25wZnBld3h1eXNobWlwemh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzA5ODIsImV4cCI6MjA3NDU0Njk4Mn0.NHISBE14TyHl6Ii1onqaDAedfVGp20G9N2ZjegSIq8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});